### ISSUE TITLE
Support showing numbers as hex

### ISSUE THREAD

**Issue by tom-sherman** [microsoft/vscode-node-debug#192] opened 2019-04-26 18:21 UTC
Right now I have to resort to horrible things like in the screenshot
![image](https://user-images.githubusercontent.com/9257001/56828099-78867800-6858-11e9-86de-b970ded232a1.png)

**Comment by weinand** [comment] 2019-05-31 09:01
duplicate of https://github.com/microsoft/vscode/issues/28025

**Closed** 2019-05-31 09:01 UTC
Labels: duplicate
