### ISSUE TITLE
Source map support not working with mocha, and minor problems with node generally

### ISSUE THREAD

**Issue by jamietre** [Microsoft/vscode-node-debug#62] opened 2016-04-11 13:56 UTC
I create a repository to reproduce the problems along with a detailed [walkthrough](https://github.com/jamietre/vscode-mocha-babel-problem/blob/master/README.md).

[https://github.com/jamietre/vscode-mocha-babel-problem](https://github.com/jamietre/vscode-mocha-babel-problem)

This behavior is the same with VS Code `0.10.11` and `0.10.14-insider`.

Running the app with node and external sourcemaps, it largely works, though there are a couple minor issues:
- Shows compiled code instead of source on initial entry breakpoint launching debugger with `--debug-brk`, but switches to source after first step
- Occasionally switches back to compiled code while stepping through code, especially right before exiting a function call

When debugging with mocha, using sourcemaps produced by inline compilation, e.g.:

```
mocha --debug-brk --compilers js:babel-core/register test
```

 it doesn't really work at all:
- A `debugger` statement in the test file breaks at the last line of the source
- when code flow enters files that were already compiled with external source map files (e.g. the code being tested) the breakpoints and code positions completely wrong

I looked at the sourcemaps produced by babel using [source map visualization](http://sokra.github.io/source-map-visualization/) and they seemed correct. I also performed the same steps using `node-inspector` and for the most part everything worked as expected there.

Thanks!

**Comment by jamietre** [comment] 2016-05-02 12:54
No response for three weeks... but this seems to be the same as other issues logged in the main vs-code repo more recently:

https://github.com/Microsoft/vscode/issues/5728
https://github.com/Microsoft/vscode/issues/5762

For node debugging issues, generally, is it preferable to post them here or in the main repo?

**Comment by weinand** [comment] 2016-06-09 11:00
@jamietre Sorry for not responding faster to the issues filed here. Yes, filing bugs against the main VS Code repo is preferred.

I tried your project in VS Code 1.2 and here are my comments:

- whenever VS Code stops in a line that is not covered by a source map, it will show the generated code and not the source (because there is no mapping). However, recently we've introduced a new (experimental) launch config setting `smartStep`. If set to `true` VS Code will automatically continue stepping through the generated code until it hits code that has a source mapping again. Please try it and let me know whether it works for you. 

- VS Code does not yet support the dynamically generated code by babel-core/register. This is tracked by https://github.com/Microsoft/vscode/issues/5728. It is scheduled for this sprint.

And thanks for the great project and readme.md.

**Comment by jamietre** [comment] 2016-06-09 13:10
No problem @weinand - i know there's a ton of churn, as evidenced by the rapid evolution of the project! I love vs code and tremendously appreciate all the work you guys have put into it, it's come such a long way even in just the last few months. I'm glad to contribute in any way I can.

And glad to hear about #5728 - I think this is the only significant problem I have in my daily use any more, everything else is just gravy.

**Comment by weinand** [comment] 2016-06-09 13:48
So I'm closing this as a duplicate of #5728.

**Comment by weinand** [comment] 2016-06-12 22:40
@jamietre I'm opening this issue because your use case was really enlightening. Here is the analysis:

Tools like node-inspector or the Chrome dev tools have no difficulties to show the executed code because they stream the code directly from node. This ensures that they really show what node.js is executing.

VS Code is a bit different because the VS Code debugger tries to map the executed code back to files in the workspace. For this the debugger uses the paths that node.js associates with the executed code. This works fine in most situations.

But it breaks with tools like Babel. These tools rewrite the code that is loaded from files in a 'require' and execute modified code. The problem with this is that Babel does not modify the path that is associated with this. When stepping into this code VS Code will map back the path to the original file in the workspace, unbeknownst that the executed code was in fact quite different.

Tools like node-inspector have no problems with this because they just show the executed code by streaming it from node.js and they ignore the path to the originating source.

I'm now trying to verify that the executed code is actually identical to the file on disk before opening the workspace file. If the file is not identical I show the executed contents (in read-only mode).
A slight complication is that node.js always wraps the file contents into a function before execution. So the code comparison has to take this into account.

With this fix I see the same behaviour with VS Code as with node-inspector when stepping through your sample. 

BTW, both tools can not (yet) use the source maps that are available in the 'dist' folder because Babel does a transformation of the code in cache.js and index.js files without adding a source map references to the resulting code. So there is no (easy) way to locate the source maps in the 'dist' folder.

Yes, with an exhaustive search they could be located, but since the source maps are not created by Babel and do not necessarily match to the executed code it is not clear how useful that would be.

**Comment by jamietre** [comment] 2016-06-28 13:45
@weinand I missed this comment before. This is very interesting. I wanted to make another observation (which may basically be what you are already saying) but there's really no point in worrying about the source maps in dist. They may not exist at all, and will certainly be out of date within any mocha/test writing session. That is

That is a typical workflow for writing a test might be just to run

`mocha --watch`

and work interactively with both test and source files. Unless I also watch my source with the main build step, which would be completely unnecessary, there will be nothing output at all to `dist` during the session.

So I'd say there's no point in worrying about that...

**Comment by jamietre** [comment] 2016-06-28 13:48
Also... just to be clear the changes you're talking about aren't yet in an insider build are they? I just tried it out with my fingers crossed but it still seems to work as before. Just want to make sure I am not missing something.

**Comment by weinand** [comment] 2016-06-28 14:12
@jamietre some preparatory work is already in the insider build, but that should not make a difference for you. The fix will come with Microsoft/vscode#5728.

**Comment by jamietre** [comment] 2016-08-25 13:22
Not sure if any recent changes should have had any impact on Mocha debugging -- I haven't seen any commits that appear directly related anyway -- but I have noticed lately that

1) Debugging in the mocha test file itself seems to work reliably (whereas it didn't used to)
2) When an imported file (e.g. the source file actually being tested) is debugged, it never does

I have basically just resorted to dropping in "debugger" statements instead of trying to use breakpoints when debugging mocha, which works well enough, but usually shows the compiled code in the imported files. Sometimes I play around with debugging config, e.g. source maps 'inline', 'both' or 'true' with babel config under my test heirarchy. In the past I feel like "both" used to work better, seems to make no difference now.

**Comment by weinand** [comment] 2017-11-20 10:14
"node-debug" (this repo) is only used for the "legacy" protocol. 
The "inspector" protocol (which is supported by recent node versions) lives in "node-debug2".

**Closed by weinand** 2017-11-20 10:14 UTC
Labels: bug
